# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

logjac_IHS <- function(dat, lambda, cluster, lambdaType) {
    .Call(`_TiKmeans_logjac_IHS`, dat, lambda, cluster, lambdaType)
}

logjac_IHS1 <- function(x, lambda) {
    .Call(`_TiKmeans_logjac_IHS1`, x, lambda)
}

IHS <- function(col, lambda) {
    .Call(`_TiKmeans_IHS`, col, lambda)
}

IHS1 <- function(val, lambda) {
    .Call(`_TiKmeans_IHS1`, val, lambda)
}

IHSAll <- function(X, lambda, lambdaType, cluster) {
    .Call(`_TiKmeans_IHSAll`, X, lambda, lambdaType, cluster)
}

IHS_WSS <- function(Xihs, clusters, K, means) {
    .Call(`_TiKmeans_IHS_WSS`, Xihs, clusters, K, means)
}

IHS_WSS_Update1 <- function(x, clusters, K, lambda) {
    .Call(`_TiKmeans_IHS_WSS_Update1`, x, clusters, K, lambda)
}

T_means <- function(Xihs, clusters, k) {
    .Call(`_TiKmeans_T_means`, Xihs, clusters, k)
}

IHS_Distance_Matrix <- function(Xihs, clusters, means, k, lambda, X, lambdaType) {
    .Call(`_TiKmeans_IHS_Distance_Matrix`, Xihs, clusters, means, k, lambda, X, lambdaType)
}

chooseLambdaMove <- function(scores, lambdaStepType) {
    .Call(`_TiKmeans_chooseLambdaMove`, scores, lambdaStepType)
}

getClosest <- function(dists) {
    .Call(`_TiKmeans_getClosest`, dists)
}

KM_Transformed_Internal <- function(X, K, centersR, lambdaType, lambdaSeq, lambdaStepType, lambdaR, maxiter) {
    .Call(`_TiKmeans_KM_Transformed_Internal`, X, K, centersR, lambdaType, lambdaSeq, lambdaStepType, lambdaR, maxiter)
}

